joystickinpu.bin:joystickinput.asm
	dasm joystickinput.asm -f3 -v0 -ojoystickinput.bin -ljoystickinput.lst -sjoystickinput.sym
run:
	stella joystickinput.bin
clean:
	rm joystickinput.bin joystickinput.sym joystickinput.lst