screenobjects.bin:screenobjects.asm
	dasm screenobjects.asm -f3 -v0 -sscreenobjects.sym -lscreenobjects.lst -oscreenobjects.bin
run:
	stella screenobjects.bin
clean:
	rm screenobjects.bin screenobjects.sym screenobjects.lst