verticalposition.bin:verticalposition.asm
	dasm verticalposition.asm -f3 -v0 -sverticalposition.sym -lverticalposition.lst -overticalposition.bin
run:
	stella verticalposition.bin
clean:
	rm verticalposition.bin verticalposition.lst verticalposition.sym