horizontalposition.bin:horizontalposition.asm
	dasm horizontalposition.asm -f3 -v0 -lhorizontalposition.lst -shorizontalposition.sym -ohorizontalposition.bin
run:
	stella horizontalposition.bin
clean:
	rm horizontalposition.bin horizontalposition.sym horizontalposition.lst